namespace: "zloveless"
name: "common"
version: "1.0.0"
readme: "README.md"
license_file: "LICENSE"
repository: "https://github.com/zloveless/ansible-common"
authors:
  - "Zack Loveless (https://zloveless.com)"
dependencies:
  "community.general": ">=3.0.0"
  "community.crypto": ">=1.9.6"
  "ansible.posix": ">=1.2.0"