---
- name: check if debian family
  ansible.builtin.fail:
    msg: "This role is only supported on the Debian family of distributions."
  when: ansible_os_family|lower != 'debian'

- name:
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - unattended-upgrades
    state: latest

- name: Copy unattended-upgrades configuration files in place.
  template:
    src: "{{ item }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - 10periodic
    - 50unattended-upgrades
#EOF
