---
- name: Set configured port fact
  ansible.builtin.set_fact:
    sshd_configured_port: "{{ ansible_port }}"

- name: Check availability of the provided ssh port on host
  ansible.builtin.wait_for:
    port: "{{ item }}"
    state: "started"
    host: "{{ ansible_ssh_host | default(ansible_host) | default(inventory_hostname) }}"
    search_regex: OpenSSH
    connect_timeout: "5"
    delay: "10"
    timeout: "10"
  delegate_to: "localhost"
  ignore_errors: true
  register: configured_ssh
  loop:
    - "{{ sshd_configured_port }}"
    - "{{ sshport_default }}"

- name: Check if the desired port is already configured
  when: not configured_ssh.results[0].failed and configured_ssh.results[0].item == ansible_port
  block:
    - name: Segue to our sponsor
      ansible.builtin.debug:
        msg: "Exiting role due to {{ inventory_hostname }} already having the correct ssh port configured."

    - name: Is the desired port is already reachable
      ansible.builtin.meta: end_host

- name: Fail if the ssh port is unreachable or unknown
  ansible.builtin.fail:
    msg: "The configured ssh port and default ssh port are unreachable. Is {{ inventory_hostname }} behind a NAT or Firewall?"
  when: configured_ssh.results[0].failed and configured_ssh.results[1].failed

- name: Reset ansible_port to default value if preferred is not configured already
  ansible.builtin.set_fact:
    ansible_port: "{{ configured_ssh.results[1].item }}" # fancy way of saying 22. (see order from loop in check availability task above)
  when: configured_ssh.results[0].failed and not configured_ssh.results[1].failed

- name: Confirm host connection works
  ansible.builtin.ping:

- name: Get openssh-server version from remote
  ansible.builtin.package_facts:
    strategy: all

- name: Update openssh_version as a fact
  ansible.builtin.set_fact:
    openssh_version: "{{ (ansible_facts.packages['openssh-server'][0].version) | ansible.builtin.regex_replace('^.*:([0-9]+\\.[0-9]+).*', '\\1') }}"

- name: Configure the SSH Port
  become: true
  block:
    - name: Include OS-specific tasks
      ansible.builtin.include_tasks: "{{ item }}"
      with_first_found:
        - "{{ ansible_distribution | lower }}_{{ ansible_distribution_major_version }}.yaml"
        - "{{ ansible_distribution | lower }}.yaml"
        - "{{ ansible_os_family }}.yaml"
      ignore_errors: true

    - name: Write port change to sshd configuration file
      ansible.builtin.lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "^Port"
        insertbefore: "^#Port"
        line: "Port {{ sshd_configured_port }}"
      notify: "Restart sshd"
      when: openssh_version is version('7.3', '<')

    - name: Install port change to /etc/ssh/sshd_config.d/ configuration.
      ansible.builtin.template:
        src: "{{ role_path }}/templates/10-sshport.conf.j2"
        dest: "/etc/ssh/sshd_config.d/10-sshport.conf"
        mode: "0600"
      notify: "Restart sshd"
      when: openssh_version is version('7.3', '>=')

- name: Ensure sshd is restarted
  ansible.builtin.meta: flush_handlers

- name: Set ansible_port to the configured ssh port
  ansible.builtin.set_fact:
    ansible_port: "{{ sshd_configured_port }}"
