---
- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
  become: true

- name: Reload firewalld
  ansible.builtin.service:
    name: firewalld
    state: reloaded
  become: true
