---
- name: Elevate privileges
  become: true
  become_user: root
  block:
    - name: Ensure packages are installed
      ansible.builtin.package:
        name:
          - systemd-container
          - docker-ce-rootless-extras
        state: present
    
    - name: Check if user has linger enabled
      ansible.builtin.stat:
        path: "{{ '/var/lib/systemd/linger/' + compose_systemd_user }}"
      register: linger
    
    - name: Enable linger on user
      ansible.builtin.command:
        argv:
          - /usr/bin/loginctl
          - enable-linger
          - "{{ compose_systemd_user }}"
      when: not linger.stat.exists

- name: "Configure docker rootless as {{ compose_systemd_user }}"
  become: true
  become_user: "{{ compose_systemd_user }}"
  block:
    - name: Check for rootless Docker systemd unit
      ansible.builtin.stat:
        path: "/home/{{ compose_systemd_user }}/.config/systemd/user/docker.service"
      register: rootless_docker_unit

    # SEE: https://github.com/ansible/ansible/issues/86298
    - name: "Configure docker rootless manually on {{ inventory_hostname }}"
      ansible.builtin.pause:
        prompt: >-
          Ansible cannot currently create the required pam_systemd session
          for {{ compose_systemd_user }} due to the machinectl/TTY issue.

          Please log in directly
              ssh -p {{ ansible_port }} {{ compose_systemd_user }}@{{ ansible_host }}
          
          and run:
              dockerd-rootless-setuptool.sh install
          
          Then return here and press Enter to continue.
        echo: false
      when: not rootless_docker_unit.stat.exists
    
    - name: Ensure docker is running on the specified user
      ansible.builtin.systemd_service:
        name: docker
        scope: user
        state: started

    - name: Create the compose project directory structure
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        recurse: true
        mode: "0600"
      loop:
        - "{{ compose_project_path }}/.docker/"
        - "{{ compose_systemd_unit_path }}"
    
    
