---

- name: Confirm requirements present
  ansible.builtin.fail:
    msg: "Unable to proceed with role. Please confirm that both compose_project_name and compose_project_yaml are set when running the role."
  when:
    - compose_project_name is not None
    - compose_project_yaml is not None 

- name: Check if docker is installed
  ansible.builtin.command: docker -v
  register: docker_check
  ignore_errors: true
  changed_when: false

- name: Fail if docker is not installed
  ansible.builtin.fail:
    msg: "Docker and Docker Compose need to be installed before using this role."
  when: docker_check.rc != 0

- name: Update project path
  ansible.builtin.set_fact:
    compose_project_path: "{{ compose_project_base_path }}/{{ compose_project_name }}"
    compose_project_file: "{{ compose_project_path }}/{{ compose_project_name }}.compose.yaml"
    compose_service_name: "{{ compose_service_prefix }}{{ compose_project_name }}"
  changed_when: false

- name: Set up rootful installation
  ansible.builtin.include_tasks: install_system.yaml
  when: state | default('present') == 'present' and compose_systemd_scope == 'system'

- name: Set up per-user installation
  ansible.builtin.include_tasks: install_user.yaml
  when: state | default('present') == 'present' and compose_systemd_scope == 'user'

- name: Install compose project
  ansible.builtin.include_tasks: install_common.yaml
  when: state | default('present') == 'present'

- name: Uninstall the project service
  ansible.builtin.include_tasks: uninstall.yaml
  when: state | default('present') == 'absent'
