---
- name: Unsupported operation. Please do the following manually.
  ansible.builtin.fail:
    msg: >-
      Uninstalling is unsupported for the role right now.
      To uninstall
      
      Please log in directly:
        ssh -p {{ ansible_port }} {{ compose_systemd_user | default(ansible_user, true) }}@{{ ansible_host }}

      and run:
        systemctl {{ '--user' if compose_systemd_scope == 'user' else '' }} disable --now {{ compose_project_service }}
