---
compose_registry_url: null
compose_registry_username: null
compose_registry_password: null

compose_systemd_user: null
compose_systemd_scope: "{{ 'user' if compose_systemd_user is not none else 'system' }}"

compose_project_name: null
compose_project_file: null
compose_project_yaml: null
compose_systemd_user_home: null
compose_project_base_path: >-
  {{
    '/opt/compose'
    if compose_systemd_scope == 'system'
    else compose_systemd_user_home ~ '/.compose_projects'
  }}

# The systemd unit base path
compose_systemd_unit_path: >-
  {{
    '/etc/systemd/system'
    if compose_systemd_scope == 'system'
    else compose_systemd_user_home + '/.config/systemd/user'
  }}

compose_systemd_become_user: >-
  {{
    compose_systemd_user
    if compose_systemd_scope == 'user'
    else 'root'
  }}

compose_service_prefix: "compose-"
